import { useEffect, useRef } from "react";
import { notifications } from "@mantine/notifications";
import { Button, Stack, Text } from "@mantine/core";
import { IconRefresh, IconCheck } from "@tabler/icons-react";
import { useIntl } from "./useIntl";

/**
 * Hook to detect and notify users about new app versions
 * Monitors Service Worker updates and shows a notification when a new version is available
 * Works with vite-plugin-pwa to detect when a new deployment is live
 */
export function useAppUpdateNotification() {
  const { getLocalizedText } = useIntl();
  const updateAvailableRef = useRef(false);
  const notificationShownRef = useRef(false);
  const workboxRef = useRef<import("workbox-window").Workbox | null>(null);

  useEffect(() => {
    // Only run in browser environment
    if (typeof window === "undefined" || !("serviceWorker" in navigator)) {
      return;
    }

    // Dynamically import workbox-window
    import("workbox-window")
      .then((module) => {
        const wb = new module.Workbox("/sw.js", { type: "module" });
        workboxRef.current = wb;

        // Listen for waiting service worker (new version available)
        wb.addEventListener("waiting", () => {
          if (!updateAvailableRef.current && !notificationShownRef.current) {
            updateAvailableRef.current = true;
            notificationShownRef.current = true;

            const handleUpdate = () => {
              // Skip waiting and reload
              wb.messageSkipWaiting();
              window.location.reload();
            };

            // Show notification with reload button
            notifications.show({
              id: "app-update-available",
              title: getLocalizedText(
                "Neue Version verfügbar",
                "New version available"
              ),
              message: (
                <Stack gap="xs">
                  <Text size="sm">
                    {getLocalizedText(
                      "Eine neue Version der App ist verfügbar.",
                      "A new version of the app is available."
                    )}
                  </Text>
                  <Button
                    size="xs"
                    leftSection={<IconRefresh size="1rem" />}
                    onClick={handleUpdate}
                    variant="light"
                  >
                    {getLocalizedText("Aktualisieren", "Update")}
                  </Button>
                </Stack>
              ),
              color: "blue",
              icon: <IconRefresh size="1.2rem" />,
              autoClose: false,
              withCloseButton: true,
              withBorder: true,
            });
          }
        });

        // Listen for controlling service worker (update installed)
        wb.addEventListener("controlling", () => {
          // Update was installed and is now controlling the page
          notifications.update({
            id: "app-update-available",
            title: getLocalizedText("App aktualisiert", "App updated"),
            message: getLocalizedText(
              "Die App wurde erfolgreich aktualisiert.",
              "The app has been successfully updated."
            ),
            color: "green",
            icon: <IconCheck size="1.2rem" />,
            autoClose: 5000,
          });
        });

        // Register the service worker
        // This will work alongside vite-plugin-pwa's registration
        // The service worker file (/sw.js) is generated by vite-plugin-pwa during build
        // When a new version is deployed, the service worker file changes (new hash/version)
        // The browser automatically detects this change and installs the new service worker
        wb.register()
          .then(() => {
            // Check for updates periodically (every 5 minutes)
            const checkForUpdates = () => {
              // This checks if the service worker file has changed on the server
              // If it has, a new service worker will be installed and the 'waiting' event fires
              wb.update().catch((error) => {
                console.error("Service Worker update check failed:", error);
              });
            };

            // Check immediately and then every 5 minutes
            checkForUpdates();
            const intervalId = setInterval(checkForUpdates, 5 * 60 * 1000);

            return () => {
              clearInterval(intervalId);
            };
          })
          .catch((error) => {
            console.error("Service Worker registration failed:", error);
          });
      })
      .catch((error) => {
        console.error("Failed to load workbox-window:", error);
      });
  }, [getLocalizedText]);
}
